# Generated by Django 3.2.7 on 2021-09-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH')], max_length=4)),
                ('course', models.CharField(choices=[('BE', 'BE'), ('MCA', 'MCA'), ('B.Tech', 'B.Tech'), ('BCA', 'BCA')], max_length=6)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
